### ISSUE TITLE
複数の原稿ファイルでセクション番号が連続しない

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/themes#129]
Vivliostyle Base Theme で、セクション番号は "1.1.1" の形式になるように設定されています：

https://github.com/vivliostyle/themes/blob/main/packages/%40vivliostyle/theme-base/css/partial/section.css#L16-L20

単一の原稿ファイルならばこれでよいですが、複数の原稿ファイルを結合する場合に、各ファイルでカウンターがリセットされるので、トップレベルのセクション（たいてい「章」をあらわす）の番号がぜんぶ "1" になってしまいます。

考えられる回避策は、次のように各原稿ファイルでセクション番号のカウンターの値をセットすることです。

2番目の原稿ファイルで
```html
<style>
h1 {
  counter-set: vs-counter-sections 2;
}
</style>
```

3番目の原稿ファイルで
```html
<style>
h1 {
  counter-set: vs-counter-sections 3;
}
</style>
```

もっとよい方法があるとよいですが……

**Comment by spring-raining** [comment]
暫定的な対策として、 以下のようなCSS変数を使ってカウンターをセットするCSS変数を追加しました 18ed51aea1248c440d1d77b2fab46450844dbbfd
```css
:root {
  --vs-section--root-counter-sections: 2;
}
```

将来的に、ドキュメント数に応じてこのCSS変数を付与するvivliostyle-cliのオプションを追加することで対応しようと思います。

**Comment by MurakamiShinyu** [comment]
別の解決方法として、カウンター `vs-counter-doc` と `vs-counter-sec-h2` 〜 `vs-counter-sec-h6` を組み合わせて使うのがよいかもしれません。例えば、`custom.css` に次のように指定します：

```css
:root {
  --vs-section--marker-display: inline;
  --vs-section--h1-marker-content: counter(vs-counter-doc);
  --vs-section--h2-marker-content: var(--vs-section--h1-marker-content) '.' counter(vs-counter-sec-h2);
  --vs-section--h3-marker-content: var(--vs-section--h2-marker-content) '.' counter(vs-counter-sec-h3);
  --vs-section--h4-marker-content: var(--vs-section--h3-marker-content) '.' counter(vs-counter-sec-h4);
  --vs-section--h5-marker-content: var(--vs-section--h4-marker-content) '.' counter(vs-counter-sec-h5);
  --vs-section--h6-marker-content: var(--vs-section--h5-marker-content) '.' counter(vs-counter-sec-h6);
}
```

この方法であれば、WebPubのHTMLファイルをVivliostyle.jsを通さないでChromeなどで閲覧する場合の次の問題も回避できます：
- #130

（ただし、Vivliostyle.jsを通さない場合 `vs-counter-doc` カウンターはincrementされないので、その番号はすべて `0` になるという問題があります。）

セクションへの参照での番号付けについては、次のように `target-text()` で `::before` 擬似要素の内容を得るようにするとよいでしょう：

```css
:root {
  --vs-section--call-content: '§' target-text(attr(href), before);
}
```

この方法をテストしたリポジトリ：
https://github.com/MurakamiShinyu/MyBasic111

WebPub: https://murakamishinyu.github.io/MyBasic111/webpub/

Test with Vivliostyle Viewer: https://vivliostyle.org/viewer/#src=https://murakamishinyu.github.io/MyBasic111/webpub/
