### ISSUE TITLE
学術用のマルチカラム可能なテーマ theme-academic-twocolumn を作る

### ISSUE THREAD

**Issue by yamasy1549** [vivliostyle/themes#17]
theme-academic にデフォルトで2段組みを適用したテーマをリリースする
https://github.com/vivliostyle/themes/tree/master/packages/%40vivliostyle/theme-academic

**Comment by yamasy1549** [comment]
追加すべきは↓のようなスタイルだけ（？）なので、theme-academicのtheme.cssをimportして↓を追加するだけでも良いかも？
```css
columns: 2;
column-gap: 5mm;
```

**Comment by yamasy1549** [comment]
段抜きのスタイルはこんな感じ

```scss
.spanner {
  column-span: all;

  img {
    max-width: 100%;
  }
}
```
